### ISSUE TITLE
Is this ride still happening with Covid-19 going on?

### ISSUE THREAD

**Issue by alexdanilowicz** [skalnik/butterlap.bike#11]
Hey all, stumbled upon this site. I've been riding Butterlap w/o ever knowing there was a group ride. Is it still going on with Covid? If so, I'd be happy to open a PR that updates it with a "Covid-19 update" text, saying that the ride is still going on (or not).

**Comment by skalnik** [comment]
Yep! Still happening.

**Comment by alexdanilowicz** [comment]
Cool! Will make a PR after work. (I created a branch, but it says permission denied when trying to push to that remote branch. Shall I fork the repo?) 

More importantly, is this language appropriate? 

> COVID-19 update: There's still a group that rides every Wednesday, but obviously there's no beer or snack sharing. Please wear a mask that fits over your nose and mouth at all times during the ride.

**Comment by skalnik** [comment]
> Cool! Will make a PR after work. (I created a branch, but it says permission denied when trying to push to that remote branch. Shall I fork the repo?)

Yeah you'll need to fork to push up a new branch with how GitHub's permissions structure works 😀
> More importantly, is this language appropriate?
> 
> > COVID-19 update: There's still a group that rides every Wednesday, but obviously there's no beer or snack sharing. Please wear a mask that fits over your nose and mouth at all times during the ride.

I think that makes sense 👍

**Comment by alexdanilowicz** [comment]
Cool! Thanks @skalnik did you make out tonight? Looking forward to joining the group ride soon. 

BTW: Love this website! Super clean!

**Comment by skalnik** [comment]
> Cool! Thanks @skalnik did you make out tonight? Looking forward to joining the group ride soon.

Yep! I was there, and I should be there this next week as well.
