### ISSUE TITLE
gratuitious scripts, sloppy design, terrible idea

### ISSUE THREAD

**Issue by theaeolianmachine** [skalnik/butterlap.bike#4]
jQuery?!? THINK OF THE KILOBYTES

who even likes bikes anyways? NOT I, GOOD SIR

jk this is great, thanks for keeping the dream alive.

**Comment by skalnik** [comment]
Hm, the heck do we use jQuery for anyway? Probably can remove it.

Thanks for the kind words ❤️ See you around!
